#!/bin/sh

file=$0
fileC=${file}.C
fileEXE=${file}.exe

ROOTLIBS="-L/usr/lib64 `$ROOTSYS/bin/root-config --glibs` -lMathCore -lMinuit"
ROOTINCDIR=`$ROOTSYS/bin/root-config --incdir`

rootcling -f MuTreeDict.C -c MuTree.h MuTreeLinkDef.h

g++ -std=gnu++11 -I${ROOTINCDIR} ${fileC} MuTreeDict.C ${ROOTLIBS} -lX11 -o ${fileEXE}
${fileEXE}

rm -f MuTreeDict.C MuTreeDict.h
rm -f ${fileEXE}
