#!/bin/sh

if [ "$#" = "1" ]; then
  file=$1
else
  echo "Usage: browseMuTree [root_file]"
  exit
fi

mkdir -p /tmp/$LOGNAME

cat <<EOF >| /tmp/$LOGNAME/browseMuTree_tmp.C
{
      gSystem->Load("$PWD/libMuTree.so");
      hfile = TFile::Open("${file}","READONLY");
      new TBrowser("CMS Browser",hfile);
      TTree* muTree = (TTree*)hfile->Get("MuTree/MUTREE");
      if (!muTree) muTree = (TTree*)hfile->Get("MUTREE");
      printf("Entries in tree: %d\n", muTree->GetEntriesFast());
}
EOF

root.exe /tmp/$LOGNAME/browseMuTree_tmp.C
